### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by anmol201212** [Mauricio-KND/mkv-mp4_converter#1]
Whenever i select on a file i get this error-  
(venv) PS D:\Projects\Youtube-Video-Downloader\mkv-mp4_converter> python mkv_to_mp4_converter.py
Select an MKV file for conversion to MP4.
Error during conversion: [WinError 2] The system cannot find the file specified

**Comment by Mauricio-KND** [comment]
I will say that you need to check if you properly installed the required libraries. Also check for your MKV file.
I developed the converter in a MacBook Pro, so I'm not sure how it works in other environments. I will clone the repo and test on Ubuntu, so maybe I will need to update the code. Feel free to branch and make a pull request if you want to update the code.

**Comment by void-mckenzie** [comment]
@anmol201212  Add ffmpeg.exe 's path to the PATH variable of your environment. (Note: Not the actual exe file, but path to the folder containing the exe file). Then it works.

**Comment by Mauricio-KND** [comment]
@void-mckenzie Feel free to branch and make a pull request if you want to update the code or the README file.
